//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarmaCounter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KarmaCounter.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string AddGroupConfirmButtonText {
            get {
                return ResourceManager.GetString("AddGroupConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group.
        /// </summary>
        internal static string AddGroupPopupTitle {
            get {
                return ResourceManager.GetString("AddGroupPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rule.
        /// </summary>
        internal static string AddRuleButtonText {
            get {
                return ResourceManager.GetString("AddRuleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string AddRuleConfirmButtonText {
            get {
                return ResourceManager.GetString("AddRuleConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding rule.
        /// </summary>
        internal static string AddRulePopupTitle {
            get {
                return ResourceManager.GetString("AddRulePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable.
        /// </summary>
        internal static string AddVariableButtonText {
            get {
                return ResourceManager.GetString("AddVariableButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to clipboard.
        /// </summary>
        internal static string CopiedMessageText {
            get {
                return ResourceManager.GetString("CopiedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to exit?.
        /// </summary>
        internal static string ExitQuestionText {
            get {
                return ResourceManager.GetString("ExitQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        internal static string GlobalGroupIndicatorText {
            get {
                return ResourceManager.GetString("GlobalGroupIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        internal static string GroupDescriptionEntryPlaceholderText {
            get {
                return ResourceManager.GetString("GroupDescriptionEntryPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group description.
        /// </summary>
        internal static string GroupDescriptionLabelText {
            get {
                return ResourceManager.GetString("GroupDescriptionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group List.
        /// </summary>
        internal static string GroupListPageTitle {
            get {
                return ResourceManager.GetString("GroupListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group members.
        /// </summary>
        internal static string GroupMembersLabelText {
            get {
                return ResourceManager.GetString("GroupMembersLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name.
        /// </summary>
        internal static string GroupNameEntryPlaceholderText {
            get {
                return ResourceManager.GetString("GroupNameEntryPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group rules.
        /// </summary>
        internal static string GroupRulesLabelText {
            get {
                return ResourceManager.GetString("GroupRulesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group type.
        /// </summary>
        internal static string GroupTypeLabelText {
            get {
                return ResourceManager.GetString("GroupTypeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string InviteConfirmButtonText {
            get {
                return ResourceManager.GetString("InviteConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invited.
        /// </summary>
        internal static string InvitedMessageText {
            get {
                return ResourceManager.GetString("InvitedMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite user.
        /// </summary>
        internal static string InviteMemberButtonText {
            get {
                return ResourceManager.GetString("InviteMemberButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inviting.
        /// </summary>
        internal static string InvitePopupTitle {
            get {
                return ResourceManager.GetString("InvitePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string JoinGroupButtonText {
            get {
                return ResourceManager.GetString("JoinGroupButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local group.
        /// </summary>
        internal static string LocalGroupCheckerLabelText {
            get {
                return ResourceManager.GetString("LocalGroupCheckerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        internal static string LocalGroupIndicatorText {
            get {
                return ResourceManager.GetString("LocalGroupIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogInButtonText {
            get {
                return ResourceManager.GetString("LogInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging In.
        /// </summary>
        internal static string LogInPopupTitle {
            get {
                return ResourceManager.GetString("LogInPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Karma.
        /// </summary>
        internal static string MemberListGlobalKarmaHeaderText {
            get {
                return ResourceManager.GetString("MemberListGlobalKarmaHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Karma.
        /// </summary>
        internal static string MemberListLocalKarmaHeaderText {
            get {
                return ResourceManager.GetString("MemberListLocalKarmaHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MemberListLoginHeaderText {
            get {
                return ResourceManager.GetString("MemberListLoginHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My groups statistics.
        /// </summary>
        internal static string MyGroupsStatsMenuOptionText {
            get {
                return ResourceManager.GetString("MyGroupsStatsMenuOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string PaymentExceptionText {
            get {
                return ResourceManager.GetString("PaymentExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string PrivateGroupIndicatorText {
            get {
                return ResourceManager.GetString("PrivateGroupIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        internal static string PrivateKeyLabelText {
            get {
                return ResourceManager.GetString("PrivateKeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public group.
        /// </summary>
        internal static string PublicGroupCheckerLabelText {
            get {
                return ResourceManager.GetString("PublicGroupCheckerLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string PublicGroupIndicatorText {
            get {
                return ResourceManager.GetString("PublicGroupIndicatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        internal static string PublicKeyLabelText {
            get {
                return ResourceManager.GetString("PublicKeyLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string RefuseText {
            get {
                return ResourceManager.GetString("RefuseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule scope.
        /// </summary>
        internal static string RuleDescriptionPlaceholderText {
            get {
                return ResourceManager.GetString("RuleDescriptionPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule violation fee formula.
        /// </summary>
        internal static string RuleFormulaPlaceholderText {
            get {
                return ResourceManager.GetString("RuleFormulaPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RuleNameHeader {
            get {
                return ResourceManager.GetString("RuleNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name.
        /// </summary>
        internal static string RuleNamePlaceholderText {
            get {
                return ResourceManager.GetString("RuleNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string RuleTextHeader {
            get {
                return ResourceManager.GetString("RuleTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUpButtonText {
            get {
                return ResourceManager.GetString("SignUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string SignUpPopupTitle {
            get {
                return ResourceManager.GetString("SignUpPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group List.
        /// </summary>
        internal static string WatchGroupListMenuOptionText {
            get {
                return ResourceManager.GetString("WatchGroupListMenuOptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string WatchProfileMenuOptionText {
            get {
                return ResourceManager.GetString("WatchProfileMenuOptionText", resourceCulture);
            }
        }
    }
}
